- name: Install Citrix and configure
  hosts: clients
  
  tasks:
  - name: Ensure system is up to date
    dnf:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - name: Remove packates not needed anymore
    dnf:
      autoremove: yes
      
  - name: Install depends
    dnf:
      name: compat-openssl11
      state: latest
