- name: Install Citrix and configure
  hosts: clients
  
  tasks:
  - name: Ensure system is up to date
    dnf:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - name: Remove packates not needed anymore
    dnf:
      autoremove: yes
      
  - name: Install desktop environment
    dnf:
      name: '@xfce-desktop-environment'
      state: latest
      
  - name: Install depends
    dnf:
      name: 'compat-openssl11'
      state: latest

  - name: Download Citrix
    copy:
      src: /root/ICAClient-rhel-22.12.0.12-0.x86_64.rpm
      dest: /root/ICAClient-rhel-22.12.0.12-0.x86_64.rpm
      
  - name: Install Citrix
    shell: dnf install /root/ICAClient-rhel-22.12.0.12-0.x86_64.rpm
