- name: Install Citrix and configure
  hosts: all

  tasks:
  - name: Ensure system is up to date
    dnf:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - name: Remove packates not needed anymore
    dnf:
      autoremove: yes

  - name: Add repos
    dnf:
      name: 'epel-release'
      state: latest

  - name: Enable repo
    warn: false
    shell: 'dnf --enablerepo=epel group'

  - name: Install desktop environment
    dnf:
      name:
        - '@xfce'

  - name: Enable GUI
    shell: 'echo "exec /usr/bin/xfce4-session" >>  ~/.xinitrc && systemctl set-default graphical'
    
  - name: Edit xfce display configs
    shell:
     - 'sed -i s/#WaylandEnable=false/WaylandEnable=false/g /etc/gdm/custom.conf'
     - 'echo "AutomaticLoginEnable = true" >> /etc/gdm/custom.conf'
     - 'echo "AutomaticLogin = vdi" >> /etc/gdm/custom.conf'

  - name: Install depends
    dnf:
      name:
        - 'compat-openssl11'
        - 'libXpm'
        - 'speexdsp'
      state: latest

  - name: Download Citrix
    copy:
      src: /root/ICAClient-rhel-22.12.0.12-0.x86_64.rpm
      dest: /root/ICAClient-rhel-22.12.0.12-0.x86_64.rpm

  - name: Install Citrix
    dnf:
      disable_gpg_check: True
      name: '/root/ICAClient-rhel-22.12.0.12-0.x86_64.rpm'
      
  - name: Create autostart directory, copy link
    ansible.builtin.file:
       path: /home/vdi/.config/autostart
       state: directory
       mode: '0755'
    copy:
       src: /usr/share/applications/selfservice.desktop
       dest: /home/vdi/autostart/selfservice.desktop
  
  - name: Configure citrix for VDI
    ansible.builtin.file:
    path: /home/vdi/.ICAClient/.eula_accepted
    state: touch
    mode: u=rw,g=r,o=r

  - name: Reboot
    reboot:
